export { NavBar } from './Navbars/navBar'
export { Footer } from './Footers/footer'
export { Hero } from './Heros/hero'
export { Form } from './Forms/form'
export { Button } from './Buttons/Button'
export { Card } from './Cards/card'