export { NavBar } from './navBar'
export { Footer } from './footer'
export { Hero } from './hero'
export { Form } from './form'
export { SliderCard} from './sliderCard'
export { CardHover } from './cardHover'